app:
    resource: '@AppBundle/Controller/'
    type: annotation
    type: rest
    prefix: /api

app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }